import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className={styles.titleWrapper}>
            <Image className={styles.titleImage} alt='couple facing river' src={"/../public/images/backfacing-head.JPG"} fill/>
            <div className={styles.titleText}>
              <p>To the love of my life:</p>
              <h1>Happy Anniversary💖💖</h1>
            </div>
          </div>
        </div>
          
      </main>
    </>
  )
}
